import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
            <Provider>
              <Navbar />
              {children}
              <Footer />
            </Provider>
          </body>
      </html>
  );
}

